package frc.robot.common.robotprovider;

import javafx.beans.property.DoubleProperty;
import javafx.beans.property.SimpleDoubleProperty;

public class FauxbotPigeonIMU extends FauxbotSensorBase implements IPigeonIMU
{
    private final DoubleProperty angleProperty;

    public FauxbotPigeonIMU(int deviceNumber)
    {
        this.angleProperty = new SimpleDoubleProperty();
        FauxbotSensorManager.set(new FauxbotSensorConnection(FauxbotSensorConnection.SensorConnector.CAN, deviceNumber), this);
    }

    /**
     * Get Yaw, Pitch, and Roll data.
     * @param ypr_deg array to fill with yaw[0], pitch[1], and roll[2] data. Yaw is within [-368,640, +368,640] degrees. Pitch is within [-90,+90] degrees. Roll is within [-90,+90] degrees.
     * @return the last error code generated.
     */
    public int getYawPitchRoll(double[] ypr_deg)
    {
        ypr_deg[0] = this.angleProperty.getValue();
        return 0;
    }

    /**
     * Sets the Yaw register to the specified value.
     * @param angleDeg New yaw in degrees [+/- 368,640 degrees]
     * @return error code generated by function. 0 indicates no error. 
     */
    public int setYaw(double angleDeg)
    {
        this.angleProperty.setValue(angleDeg);
        return 0;
    }

    /**
     * Gets the current Pigeon state
     * @return pigeon state value
     */
    public PigeonState getState()
    {
        return PigeonState.Ready;
    }

    public void enterTemperatureCalibrationMode()
    {
    }

    public DoubleProperty getProperty()
    {
        return this.angleProperty;
    }
}